<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAx7WUgE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAx7WUgE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAx7WUgE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAx7WUgE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAx7WUgE\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ax7WUgE',
    'container.build_id' => '0eb26f5b',
    'container.build_time' => 1591800754,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAx7WUgE');
