<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerT3epSVT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerT3epSVT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerT3epSVT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerT3epSVT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerT3epSVT\App_KernelDevDebugContainer([
    'container.build_hash' => 'T3epSVT',
    'container.build_id' => '98b7142b',
    'container.build_time' => 1622544233,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerT3epSVT');
